# Generated by Django 4.2.1 on 2023-06-13 12:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="dob",
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
