# Generated by Django 4.2.1 on 2023-06-22 09:43

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_user_dob"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dob",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="user",
            name="confirm_password",
            field=models.CharField(max_length=255, null=False),
        ),
    ]
