# Generated by Django 4.2.1 on 2023-08-22 09:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_dob"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="confirm_password",
        ),
    ]
