# Generated by Django 4.2.1 on 2023-06-30 02:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
