# Generated by Django 4.2.1 on 2023-06-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('estimate', models.IntegerField()),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('started', 'Started'), ('finished', 'Finished'), ('delivered', 'Delivered')], max_length=255)),
                ('is_scheduled', models.CharField(choices=[('scheduled', 'Scheduled'), ('not_scheduled', 'Not Scheduled')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
