# Generated by Django 4.2.1 on 2023-06-12 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='story',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='story',
            name='is_scheduled',
            field=models.IntegerField(choices=[(1, 'Scheduled'), (2, 'Not Scheduled')], default=2),
        ),
        migrations.AlterField(
            model_name='story',
            name='status',
            field=models.IntegerField(choices=[(1, 'Not Started'), (2, 'Started'), (3, 'Finished'), (4, 'Delivered')], default=1),
        ),
    ]
