version: '3'

services:
  frontendapp:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    image: frontendapp
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_BASE_URL=http://localhost:8000
